# Generated by Django 5.2.3 on 2025-08-13 00:38

import django.db.models.deletion
import uuid
import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone/WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Padrão', max_length=80, verbose_name='Nome da credencial')),
                ('access_token', models.TextField(verbose_name='Access Token (Mercado Pago)')),
                ('public_key', models.CharField(blank=True, max_length=120, verbose_name='Public Key (opcional)')),
                ('webhook_secret', models.CharField(blank=True, max_length=120, verbose_name='Webhook secret (opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Pagamento',
                'verbose_name_plural': 'Credenciais de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('checkout_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produtos/imagens/', verbose_name='Imagem')),
                ('video_url', models.URLField(blank=True, verbose_name='Vídeo (URL)')),
                ('digital_file', models.FileField(upload_to='produtos/arquivos/', verbose_name='Arquivo digital')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('payment_type', models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão')], db_index=True, default='pix', max_length=10, verbose_name='Forma de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=vendas.models.default_order_expiry, verbose_name='Expira em')),
                ('gateway', models.CharField(default='mercadopago', max_length=40)),
                ('preference_id', models.CharField(blank=True, max_length=120)),
                ('external_ref', models.CharField(blank=True, help_text='Ex: order-<id>', max_length=120)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='MP Payment ID')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='Pix copia-e-cola')),
                ('pix_qr_base64', models.TextField(blank=True, verbose_name='QR base64')),
                ('pix_ticket_url', models.URLField(blank=True, verbose_name='Ticket URL')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='Bandeira')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Final')),
                ('card_holder', models.CharField(blank=True, max_length=120, verbose_name='Titular')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendas.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendas.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_link', to='vendas.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='vendas_orde_status_09bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type'], name='vendas_orde_payment_3ecff3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='vendas_orde_created_c4fa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='vendas_orde_product_d2f314_idx'),
        ),
    ]
