# Generated by Django 5.2.3 on 2025-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Padrão', max_length=80, verbose_name='Nome da credencial')),
                ('access_token', models.TextField(verbose_name='Access Token (Mercado Pago)')),
                ('public_key', models.CharField(blank=True, max_length=120, verbose_name='Public Key (opcional)')),
                ('webhook_secret', models.CharField(blank=True, max_length=120, verbose_name='Webhook secret (opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Pagamento',
                'verbose_name_plural': 'Credenciais de Pagamento',
            },
        ),
    ]
