# Generated by Django 5.2.3 on 2025-08-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_product_digital_file_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='produtos/arquivos/', verbose_name='Arquivo digital'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/imagens/', verbose_name='Imagem'),
        ),
    ]
