# Generated by Django 5.2.3 on 2025-08-12 16:28

import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_paymentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bandeira'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Final'),
        ),
        migrations.AddField(
            model_name='order',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='MP Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão')], db_index=True, default='pix', max_length=10, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_qr_base64',
            field=models.TextField(blank=True, verbose_name='QR base64'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_qr_code',
            field=models.TextField(blank=True, verbose_name='Pix copia-e-cola'),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_ticket_url',
            field=models.URLField(blank=True, verbose_name='Ticket URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=vendas.models.default_order_expiry, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Ex: order-<id>', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='vendas_orde_status_09bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type'], name='vendas_orde_payment_3ecff3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='vendas_orde_created_c4fa6e_idx'),
        ),
    ]
