# Generated by Django 5.2.3 on 2025-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_product_digital_file_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_active',
            field=models.BooleanField(default=False, verbose_name='Promoção ativa?'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional (R$)'),
        ),
    ]
