# Generated by Django 5.2.3 on 2025-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_order_card_brand_order_card_holder_order_card_last4_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='vendas_orde_product_d2f314_idx'),
        ),
    ]
