# Generated by Django 5.2.3 on 2025-08-13 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_product_promo_active_product_promo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=160, verbose_name='Razão social')),
                ('trade_name', models.CharField(blank=True, max_length=160, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(help_text='Ex.: 12.345.678/0001-95', max_length=18, unique=True, verbose_name='CNPJ')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('phone_e164', models.CharField(blank=True, help_text='Ex.: +556300000000', max_length=20, validators=[django.core.validators.RegexValidator(message='Use o formato internacional (E.164), ex.: +556300000000', regex='^\\+\\d{10,15}$')], verbose_name='Telefone (E.164)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/logos/', verbose_name='Logo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
