# Generated by Django 5.2.3 on 2025-08-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Físico')], db_index=True, default='digital', max_length=10, verbose_name='Tipo de produto'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=40, verbose_name='Apelido (ex.: Casa, Trabalho)')),
                ('recipient_name', models.CharField(blank=True, max_length=160, verbose_name='Nome do destinatário')),
                ('zip_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=160, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=80, verbose_name='Complemento')),
                ('district', models.CharField(max_length=120, verbose_name='Bairro')),
                ('city', models.CharField(max_length=120, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(default='Brasil', max_length=60, verbose_name='País')),
                ('is_default', models.BooleanField(default=False, verbose_name='Endereço padrão?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='vendas.customer')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendas.address'),
        ),
    ]
