# Generated by Django 5.2.3 on 2025-08-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_rename_zip_code_address_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Postado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=80, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Código de rastreio'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_code'], name='vendas_orde_trackin_866135_idx'),
        ),
    ]
