# Generated by Django 5.2.3 on 2025-08-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_order_shipped_at_order_tracking_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='vendas_orde_trackin_866135_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pendente de envio'), ('shipped', 'Enviado')], db_index=True, default='pending', max_length=12, verbose_name='Status de envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=40, verbose_name='Transportadora/Serviço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Código de rastreio'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_status'], name='vendas_orde_shippin_9b1430_idx'),
        ),
    ]
