"""
Django settings for loja project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
import os

# Caminhos base
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Segurança / Debug (dev) ---
SECRET_KEY = 'django-insecure-f#bkh*7ca_)d@f^ic58ya@1ksk_-q+t0xcl&-@te9y^7^5vy%1'
DEBUG = True

# Em dev, vamos permitir localhost/127.0.0.1
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# --- Apps ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendas',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loja.urls'

# --- Templates (usa templates do app) ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # mantemos vazio e usamos APP_DIRS
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loja.wsgi.application'

# --- Banco de dados (SQLite para dev) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Validações de senha ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internacionalização ---
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Araguaina'
USE_I18N = True
USE_TZ = True

# --- Arquivos estáticos e de mídia ---
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Login/Logout ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# --- Ajustes para dev sem HTTPS ---
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Alguns navegadores exigem origem confiável para POST (login/formulários)
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # Em produção, adicione seu domínio HTTPS, por exemplo:
    # 'https://sua-loja.com',
    # 'https://*.ngrok-free.app',
]

# --- Primary key default ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================
#  Mercado Pago (credenciais)
# ===========================
# Em dev/local pode deixar vazio. Em produção, configure via variáveis de ambiente.
MP_ACCESS_TOKEN = os.getenv("MP_ACCESS_TOKEN", "")
MP_PUBLIC_KEY = os.getenv("MP_PUBLIC_KEY", "")
# Em produção PRECISA ser HTTPS público
MP_WEBHOOK_URL = os.getenv("MP_WEBHOOK_URL", "")

# =========
#  Logging
# =========
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "vendas": {"handlers": ["console"], "level": "INFO"},
        "vendas.views": {"handlers": ["console"], "level": "INFO"},
        "mercadopago": {"handlers": ["console"], "level": "WARNING"},
        "django.request": {"handlers": ["console"], "level": "WARNING"},
    },
}

# =======================
#  E-mail (Opção B - SMTP)
# =======================
# Exemplo para GMAIL (recomendado usar SENHA DE APP com 2FA ativado)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"            # Para Outlook/Office 365: "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "yarinemanuelle7@gmail.com"   # <-- coloque seu e-mail aqui
EMAIL_HOST_PASSWORD = "gxir mcgn edke zgvm" # <-- senha de app (ou senha SMTP do seu provedor)
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 15

DEFAULT_FROM_EMAIL = "YARIN IMPRESSÕES <seuemail@gmail.com>"
SERVER_EMAIL = "YARIN IMPRESSÕES <seuemail@gmail.com>"

# Base pública para montar URLs em e-mails (usada quando não temos 'request')
SITE_BASE_URL = "http://localhost:8000"  # em produção: "https://sualoja.com"
