# Generated by Django 5.2.3 on 2025-08-19 10:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('razao_social', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('unidade_compra', models.CharField(choices=[('UN', 'Unidade'), ('FOLHA', 'Folha'), ('RESMA', 'Resma (500 folhas)'), ('ML', 'Mililitro'), ('L', 'Litro'), ('G', 'Grama'), ('KG', 'Quilo'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('CX', 'Caixa')], default='UN', max_length=10)),
                ('quantidade_compra', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('custo_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade_base', models.CharField(choices=[('UN', 'Unidade'), ('FOLHA', 'Folha'), ('RESMA', 'Resma (500 folhas)'), ('ML', 'Mililitro'), ('L', 'Litro'), ('G', 'Grama'), ('KG', 'Quilo'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('CX', 'Caixa')], default='UN', max_length=10)),
                ('fator_conversao_para_base', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Ex.: Resma→Folha = 500; Caixa→Unidade = qtd de itens na caixa.', max_digits=12)),
                ('perda_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% de perda média ao usar (corte, testes etc.)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('validade_dias', models.PositiveIntegerField(default=7)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('acrescimo_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_total_cache', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='precificacao.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosGlobais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_lucro_padrao', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6)),
                ('acrescimo_padrao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('desconto_max_percentual', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('impostos_percentual_sobre_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('taxa_cartao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('custo_energia_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_internet_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outros_custos_fixos_mensais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_tinta_por_percentual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('arredondar_para', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('incluir_taxas_no_preco_base', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_producao_minutos', models.PositiveIntegerField(default=0)),
                ('usa_percentual_tinta', models.BooleanField(default=False)),
                ('percentual_tinta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('margem_lucro_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('custo_estimado_cache', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('preco_sugerido_cache', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao_externa', models.CharField(blank=True, max_length=200)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='precificacao.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='precificacao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal_desejada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_trabalho_mes', models.PositiveIntegerField(default=22)),
                ('horas_por_dia', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='precificacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_uso', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('perda_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='precificacao.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='precificacao.produto')),
            ],
            options={
                'unique_together': {('produto', 'materia_prima')},
            },
        ),
    ]
